# Site settings
title: Vincent Pham
email: vincent.pham69006@gmail.com
url: https://github.com/VincentPHAM98
description: "This is Vincent PHAM's portfolio, I'm a C++ / graphics programmer based in Lyon, France."
keywords: "Vincent PHAM, C++, Graphics Programmer, Lyon, France, Developper, Portfolio"
skills: "C++ Developer - Graphics Programmer"
meta_author: PHAM Vincent

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 262A10 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: e8985e #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/VincentPHAM98

# Postal address (add as many lines as necessary)
address:
  - line: Lyon
  - line: France

# Credits content
credits: 'vincent.pham69006@gmail.com'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
